### ISSUE TITLE
Feature request: heading decorators in outline pane

### ISSUE THREAD

**Issue by rafjaf** [dragonish/obsidian-heading-decorator#2]
Hello, thank you very much for your great plugin!

It would be great if the headings numbering could also apply to the outline pane.

Presently, I am using some CSS snippet:

```css
/* == outline headings numbering == */
/* container of first layer headings. */
[data-type=outline] .view-content {
  counter-reset: rootCounter;
}

[data-type=outline] .view-content .tree-item .tree-item-self .tree-item-inner::before {
  content: counters(rootCounter, ".") ". ";
  counter-increment: rootCounter;
}

/* container of the other headings. */
/* NOTE: It is not .outline anymore. So we need a new counter */
.view-content .tree-item-children {
  counter-reset: innerCounter;
}

.view-content .tree-item-children .tree-item .tree-item-self .tree-item-inner::before {
  content: counters(rootCounter, ".") "." counters(innerCounter, ".") ". ";
  counter-increment: innerCounter;
}
```
However, the numbering is not accurate because apparently the full outline is not loaded in one go but is partly held in cache.

Thank you in advance if you have the time to help!
